### ISSUE TITLE
Wiki page suggestions

### ISSUE THREAD

**Issue by mbrush** [TranslatorSRI/CQS#12]
A couple questions/suggestions about the followign text on https://github.com/TranslatorSRI/CQS/wiki:

> Transform the Results such that a new result is added, where CQS ("infores:cqs") is the infores:primary-knowledge-source and Auxiliary (Support) Graphs are added.

- First. retrieval source metadata is added to edges, not Results - so I assume this is saying that the CQS will be added as the primary knowledge source of the 'treats' prediction edge created by the CQS.
- Second, recall that we had tentatively decided that for KP-defined one-hop predictions, the KP should be the primary source, not the CQS.  Instead, the CQS would be captured as an aggregator knowledge source.   See the table [here](https://docs.google.com/spreadsheets/d/1A5rYda3z26zaw8T64pU-F9O8qMRwo30eI14gW4ny310/edit#gid=1996781039) . . . are we all good with this?

**Comment by karafecho** [comment]
Your comments make sense to me, @mbrush. I clarified the text related to both comments. I also created a PR for Jason to test a customized approach for designating the CQS as primary vs aggregator knowledge source, as we discussed.
